vich_uploader:
    db_driver: orm

    mappings:
        shop_image:
            uri_prefix: /images/shop
            upload_destination: '%kernel.project_dir%/public/images/shop'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
