vich_uploader:

    db_driver: orm

    mappings:
       posts:
            uri_prefix: /images/Posts
            upload_destination: '%kernel.project_dir%/public/images/Posts'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
       users:
            uri_prefix: /images/users
            upload_destination:  '%kernel.project_dir%/public/images/users'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true